// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {number} fileID
 * @returns {$CancellablePromise<void>}
 */
export function CacheMediaFile(fileID) {
    return $Call.ByID(2346990641, fileID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelDownload() {
    return $Call.ByID(2195907243);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseOutputFolder() {
    return $Call.ByID(1715745561);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseAbout() {
    return $Call.ByID(2906809692);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseFileInfo() {
    return $Call.ByID(3050780857);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFileAtIndex(index) {
    return $Call.ByID(2824212482, index);
}

/**
 * @returns {$CancellablePromise<$models.Album | null>}
 */
export function GetActiveAlbum() {
    return $Call.ByID(2226617076).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AlbumHistoryEntry[]>}
 */
export function GetAlbumHistory() {
    return $Call.ByID(2223999162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DownloadProgress>}
 */
export function GetDownloadProgress() {
    return $Call.ByID(4034910168).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<number[]>}
 */
export function GetDownloadedFileIndices() {
    return $Call.ByID(3721437933).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<$models.FileDetails | null>}
 */
export function GetFileDetails(index) {
    return $Call.ByID(743151101, index).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetFileInfoIndex() {
    return $Call.ByID(2517899523);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetOutputFolder() {
    return $Call.ByID(2013226558);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetPreviewIndex() {
    return $Call.ByID(3203079179);
}

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function GetSettings() {
    return $Call.ByID(2857995934).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenAbout() {
    return $Call.ByID(2205366118);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileInfo(index) {
    return $Call.ByID(2181628175, index);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenOutputFolder() {
    return $Call.ByID(3648207368);
}

/**
 * @param {number} startIndex
 * @returns {$CancellablePromise<void>}
 */
export function OpenPreview(startIndex) {
    return $Call.ByID(2466093983, startIndex);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(1580939618);
}

/**
 * @param {number} fileID
 * @returns {$CancellablePromise<string>}
 */
export function ResolveMediaURL(fileID) {
    return $Call.ByID(2911319234, fileID);
}

/**
 * @param {$models.AppSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(1783778745, settings);
}

/**
 * @param {string} raw
 * @returns {$CancellablePromise<$models.Album | null>}
 */
export function ScrapeAlbum(raw) {
    return $Call.ByID(2843190784, raw).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetOutputFolder(path) {
    return $Call.ByID(3207040754, path);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetPreviewIndex(index) {
    return $Call.ByID(1971076071, index);
}

/**
 * @param {$models.DownloadOptions} opts
 * @returns {$CancellablePromise<void>}
 */
export function StartDownload(opts) {
    return $Call.ByID(2197712263, opts);
}

/**
 * @param {string} raw
 * @returns {$CancellablePromise<string>}
 */
export function ValidateURL(raw) {
    return $Call.ByID(3374266632, raw);
}

// Private type creation functions
const $$createType0 = $models.Album.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AlbumHistoryEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.DownloadProgress.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.FileDetails.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.AppSettings.createFrom;
