// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Album {
    /**
     * Creates a new Album instance.
     * @param {Partial<Album>} [$$source = {}] - The source object to create the Album.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("totalSize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["totalSize"] = "";
        }
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {AlbumFile[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Album}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField4_0($$parsedSource["files"]);
        }
        return new Album(/** @type {Partial<Album>} */($$parsedSource));
    }
}

export class AlbumFile {
    /**
     * Creates a new AlbumFile instance.
     * @param {Partial<AlbumFile>} [$$source = {}] - The source object to create the AlbumFile.
     */
    constructor($$source = {}) {
        if (!("fileID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileID"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("mimeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["size"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("previewURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["previewURL"] = "";
        }
        if (!("fileURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AlbumFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumFile(/** @type {Partial<AlbumFile>} */($$parsedSource));
    }
}

export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("outputFolder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputFolder"] = "";
        }
        if (!("filterTypes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["filterTypes"] = [];
        }
        if (!("includePatterns" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["includePatterns"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filterTypes" in $$parsedSource) {
            $$parsedSource["filterTypes"] = $$createField1_0($$parsedSource["filterTypes"]);
        }
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class DownloadOptions {
    /**
     * Creates a new DownloadOptions instance.
     * @param {Partial<DownloadOptions>} [$$source = {}] - The source object to create the DownloadOptions.
     */
    constructor($$source = {}) {
        if (!("types" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["types"] = [];
        }
        if (!("includePatterns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["includePatterns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadOptions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField0_0($$parsedSource["types"]);
        }
        if ("includePatterns" in $$parsedSource) {
            $$parsedSource["includePatterns"] = $$createField1_0($$parsedSource["includePatterns"]);
        }
        return new DownloadOptions(/** @type {Partial<DownloadOptions>} */($$parsedSource));
    }
}

export class DownloadProgress {
    /**
     * Creates a new DownloadProgress instance.
     * @param {Partial<DownloadProgress>} [$$source = {}] - The source object to create the DownloadProgress.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cancelled"] = false;
        }
        if (!("currentName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentName"] = "";
        }
        if (!("currentIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentIndex"] = 0;
        }
        if (!("currentBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentBytes"] = 0;
        }
        if (!("currentTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentTotal"] = 0;
        }
        if (!("completedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completedCount"] = 0;
        }
        if (!("totalCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalCount"] = 0;
        }
        if (!("fileStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileStatus"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadProgress(/** @type {Partial<DownloadProgress>} */($$parsedSource));
    }
}

export class FileDetails {
    /**
     * Creates a new FileDetails instance.
     * @param {Partial<FileDetails>} [$$source = {}] - The source object to create the FileDetails.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("fileID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileID"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("mimeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["size"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("previewURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["previewURL"] = "";
        }
        if (!("fileURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileURL"] = "";
        }
        if (!("mediaURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mediaURL"] = "";
        }
        if (!("mediaURLError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mediaURLError"] = "";
        }
        if (!("onDisk" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["onDisk"] = false;
        }
        if (!("diskPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["diskPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDetails instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileDetails}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileDetails(/** @type {Partial<FileDetails>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AlbumFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
